apiVersion: apps/v1
kind: Deployment
metadata:
  name: benotes-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: benotes-app
  template:
    metadata:
      labels:
        app: benotes-app
    spec:
      initContainers:
      - name: migrate
        image: balaji93bobby/benotes-app:${DOCKER_IMAGE_TAG}
        command: ['sh', '-c', 'php artisan migrate -n --force && php artisan db:seed -n --force']
        envFrom:
        - secretRef:
            name: my-secret
      containers:
      - name: benotes-app
        image: balaji93bobby/benotes-app:${DOCKER_IMAGE_TAG}
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: my-secret
