apiVersion: apps/v1
kind: Deployment
metadata:
  name: benotes-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: benotes-app
  template:
    metadata:
      labels:
        app: benotes-app
    spec:
      initContainers:
      - name: migrate
        image: balaji93bobby/benotes-app:${DOCKER_IMAGE_TAG}
        command: ['sh', '-c', 'php artisan key:generate', 'php artisan jwt:token', 'php artisan migrate', 'php artisan db:seed']
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD
      containers:
      - name: benotes-app
        image: balaji93bobby/benotes-app:${DOCKER_IMAGE_TAG}
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD
