apiVersion: v1
kind: Service
metadata:
  name: benotes-app-service
spec:
  selector:
    app: benotes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
  type: NodePort
